### ISSUE TITLE
Label Clarification - Semester vs Term

### ISSUE THREAD

**Issue by mdjohns** [ualr-htcpcp/dcia#57]
I'm noticing that the "SO Scores by TERM" graph is the only place we refer to this as a term. The page for managing terms is called "Semesters."

I'm thinking we might want to pick term or semester and go with that for both.

**Comment by mdjohns** [comment]
@jcypret what do we think about addressing this? Could I just rename to SO Scores by SEMESTER and call it good?

**Comment by jcypret** [comment]
Yeah, I like that 👍
