### ISSUE TITLE
Seeder failing due to name regex for apostrophe in names

### ISSUE THREAD

**Issue by mdjohns** [ualr-htcpcp/dcia#78]
We need to revisit the regex we're using to validate names (`src/utils/validation.js`).

I just had a re-seed of the database fail because the name had an apostrophe:
```
  errors: {
    'name.last': ValidatorError: Path `name.last` is invalid (O'Kon).
```

Maybe we can add an apostrophe and dash to be safe?

**Comment by jcypret** [comment]
Yeah, I ran into the same issue multiple times this evening. Totally agree this validation should be relaxed.
